# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches:
      - main

env:
  KUBECONFIG_DIR: ./.kube
  KUBECONFIG: ./.kube/config

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Write Kubeconfig to File
        shell: bash
        run: |-
          mkdir ${{ env.KUBECONFIG_DIR }}
          echo "${{ secrets.KUBECONFIG_RAW }}" > ${{ env.KUBECONFIG }}

      - name: Add Helm Repo
        shell: bash
        run: >-
          helm --kubeconfig ${{ env.KUBECONFIG }} helm repo add ${{ vars.VW_HELM_CHART }} https://guerzon.github.io/vaultwarden

      - name: Install or Upgrade Vaultwarden
        shell: bash
        run: >-
          helm --kubeconfig ${{ env.KUBECONFIG }} --namespace ${{ vars.K8S_NAMESPACE }} upgrade ${{ vars.VW_HELM_RELEASE }} ${{ vars.VW_HELM_CHART }} --values vaultwarden_values/vaultwarden.yml --values vaultwarden_values/vaultwarden_development.yml --set adminToken.value=${{ secrets.ADMIN_TOKEN }} --version ${{ vars.VW_HELM_VERSION }} --install --cleanup-on-fail --wait